zhk: zhk.c gph_io.c
	gcc -Wall -pedantic -std=c11 zhk.c gph_io.c -o zhk

dfs: dfs.c gph_io.c
	gcc -Wall -pedantic -std=c11 dfs.c gph_io.c -o dfs

free_test: free_test.c gph_io.c
	gcc -Wall -pedantic -std=c11 free_test.c gph_io.c -o free_test

test_read_graph: test_read_graph.c gph_io.c
	gcc -Wall -pedantic -std=c11 test_read_graph.c gph_io.c -o test_read_graph

test_read_matrix: test_read_matrix.c gph_io.c
	gcc -Wall -pedantic -std=c11 test_read_matrix.c gph_io.c -o test_read_matrix
