test_read_graph: test_read_graph.c gph_io.c
	gcc -Wall -pedantic -std=c11 test_read_graph.c gph_io.c -o test_read_graph

test_read_matrix: test_read_matrix.c gph_io.c
	gcc -Wall -pedantic -std=c11 test_read_matrix.c gph_io.c -o test_read_matrix
